"""Remove unique attribute from label.name

Revision ID: 56b276095242
Revises: f5bc5c7d4158
Create Date: 2017-02-05 18:25:51.034304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b276095242'
down_revision = 'f5bc5c7d4158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_name_key', 'project', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_name_key', 'project', ['name'])
    # ### end Alembic commands ###
